CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    admin BOOLEAN  DEFAULT false NOT NULL,
    active BOOLEAN NOT NULL    
);